name: Chat
version: ${project.version}
api-version: 1.12.2
description: </>


author: KeksGauner
website: https://byaple.de

loadbefore: [BankSystem]
softdepend: [BankSystem]

main: de.byaple.chat.Main

commands:
  chat:
  broadcast:
    aliases: [bc]